# File used to make requests to server (e.g., using Rest Client - vscode)
@baseUrl = http://localhost:3000
###

GET {{baseUrl}}/quotes/choices
Content-Type: application/json
Authorization: Token YOUR_TOKEN_HERE